version: "3.8"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: case_study       # Veritabanı adı
      POSTGRES_USER: user           # Kullanıcı adı
      POSTGRES_PASSWORD: password   # Şifre
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro  # (isteğe bağlı SQL dosyası)

  scraper:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/src
    environment:
      DB_URL: postgresql://user:password@postgres:5432/case_study
      DOCKER_ENV: "true"

volumes:
  pg_data:
